# Generated by Django 3.0.5 on 2020-04-18 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.CharField(max_length=100)),
                ('association_address', models.CharField(max_length=100)),
                ('association_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('company_description', models.CharField(max_length=1000)),
                ('company_association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Association')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_qualifications', models.CharField(max_length=1000)),
                ('job_date', models.DateTimeField(verbose_name='date posted')),
                ('job_status', models.CharField(max_length=100)),
                ('job_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_last_name', models.CharField(max_length=100)),
                ('employee_email', models.CharField(max_length=100)),
                ('is_employer', models.CharField(max_length=100)),
                ('employee_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_last_name', models.CharField(max_length=100)),
                ('applicant_email', models.CharField(max_length=100)),
                ('applicant_password', models.CharField(max_length=100)),
                ('applicant_address', models.CharField(max_length=100)),
                ('applicant_resume', models.CharField(max_length=1000)),
                ('application_status', models.CharField(max_length=100)),
                ('applicant_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Job'))
            ],
        ),
    ]
