# Generated by Django 3.0.5 on 2020-04-04 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_last_name', models.CharField(max_length=100)),
                ('applicant_resume', models.CharField(max_length=500)),
                ('application_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=100)),
                ('company_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_last_name', models.CharField(max_length=100)),
                ('employee_email', models.CharField(max_length=100)),
                ('employee_address', models.CharField(max_length=100)),
                ('employee_resume', models.CharField(max_length=500)),
                ('employee_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_date', models.DateTimeField(verbose_name='date posted')),
                ('job_status', models.CharField(max_length=100)),
                ('job_applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Applicant')),
                ('job_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Search_Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SC_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Employee')),
                ('SC_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_search_committee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Search_Committee'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Employee'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Job'),
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_name', models.CharField(max_length=100)),
                ('association_address', models.CharField(max_length=100)),
                ('association_description', models.CharField(max_length=200)),
                ('association_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Company')),
            ],
        ),
    ]
