# Generated by Django 3.0.5 on 2020-04-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='association_company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_employee',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_applicant',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_search_committee',
        ),
        migrations.AddField(
            model_name='applicant',
            name='applicant_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Job'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Association'),
        ),
        migrations.DeleteModel(
            name='Search_Committee',
        ),
    ]
