# Generated by Django 3.0.5 on 2020-04-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='applicant_job',
        ),
        migrations.AddField(
            model_name='applicant',
            name='applicant_job',
            field=models.ManyToManyField(to='polls.Job'),
        ),
    ]
