# Generated by Django 3.0.5 on 2020-04-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200420_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='applicant_title',
        ),
    ]
